name = "LeanLangur"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanLangur"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[lean_lib]]
name = "LeanLangur"

[[lean_lib]]
name = "LeanLangur.Draft"

[[lean_lib]]
name = "LeanLangur.MonkeyTricks"

[[lean_exe]]
name = "quicksort"